# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./MTBS.APIGateway/Dockerfile
            image: docker.io/aludanszki/apigateway
          - dockerfile: ./MTBS.BasketAPI/Dockerfile
            image: docker.io/aludanszki/basketapi
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./MovieTicketBooking.sln
    - name: Build
      run: dotnet build ./MovieTicketBooking.sln --no-restore
    - name: Test
      run: dotnet test ./MovieTicketBooking.sln --no-build --verbosity normal
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: aludanszki/mtb
        registry: docker.io
        dockerfile: ${{ matrix.dockerfile }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
      
